import os
import csv

# Define paths
CONV_ID = "71e7b1d1-f50b-477e-a713-942e8319b97d"
WORKSPACE_DIR = r"c:\Users\HP\OneDrive\Documents\AG2OSINTNEOMAXX"
ARTIFACTS_DIR = r"C:\Users\HP\.gemini\antigravity\brain\71e7b1d1-f50b-477e-a713-942e8319b97d"

# Ensure directories exist
os.makedirs(WORKSPACE_DIR, exist_ok=True)
os.makedirs(ARTIFACTS_DIR, exist_ok=True)

# Schema fields
headers = [
    "Case_ID", "Date", "Category", "Subcategory", "Entity_Name", "Individual_Name",
    "Role_Title", "License_Type", "Incident_Description", "Legal_Basis_Statute",
    "Jurisdiction", "Reporting_Deadline", "Penalties_For_Noncompliance",
    "Source_Reference", "Source_URL", "Status", "Outcome", "Notes", "Linked_Case_IDs"
]

# Case rows
cases = [
    # CASE-001
    {
        "Case_ID": "CASE-001",
        "Date": "2021-12-01",
        "Category": "Bureaucratic Blockade",
        "Subcategory": "Intake Denial",
        "Entity_Name": "Huntington Beach Police Department",
        "Individual_Name": "Kristy Conway",
        "Role_Title": "Case Manager",
        "License_Type": "None",
        "Incident_Description": "Denied employment support and funneled individual into Navigation Center instead",
        "Legal_Basis_Statute": "None",
        "Jurisdiction": "Local",
        "Reporting_Deadline": "None",
        "Penalties_For_Noncompliance": "None",
        "Source_Reference": "Personal account (December 2021)",
        "Source_URL": "N/A",
        "Status": "Documented",
        "Outcome": "Pending",
        "Notes": "Key witness",
        "Linked_Case_IDs": "CASE-002"
    },
    # CASE-002
    {
        "Case_ID": "CASE-002",
        "Date": "2023-01-15",
        "Category": "Financial Conflict",
        "Subcategory": "Undisclosed Kickback",
        "Entity_Name": "Mercy House Board of Directors",
        "Individual_Name": "Tom Conway",
        "Role_Title": "Board Member (24 yrs)",
        "License_Type": "Series 3 (possibly)",
        "Incident_Description": "0.9% retirement plan kickback through Diversified Investment Services (DIS)",
        "Legal_Basis_Statute": "SEC Investment Advisers Act of 1940",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "Annual D&O questionnaire",
        "Penalties_For_Noncompliance": "Potential SEC enforcement",
        "Source_Reference": "Mercy House Form 990 (2022)",
        "Source_URL": "https://projects.propublica.org/nonprofits",
        "Status": "Under Investigation",
        "Outcome": "Pending",
        "Notes": "Need to verify DIS connection",
        "Linked_Case_IDs": "CASE-001"
    },
    # CASE-003
    {
        "Case_ID": "CASE-003",
        "Date": "2023-06-01",
        "Category": "Network Connection",
        "Subcategory": "Family/Business Link",
        "Entity_Name": "Conway Network",
        "Individual_Name": "Kristy & Tom Conway",
        "Role_Title": "Multiple",
        "License_Type": "None",
        "Incident_Description": "Shared surname + both operate in Orange County homeless industrial complex",
        "Legal_Basis_Statute": "None",
        "Jurisdiction": "Local",
        "Reporting_Deadline": "None",
        "Penalties_For_Noncompliance": "None",
        "Source_Reference": "Public records search pending",
        "Source_URL": "N/A",
        "Status": "Unconfirmed",
        "Outcome": "Need marriage certificate or business filing",
        "Notes": "",
        "Linked_Case_IDs": "CASE-001,CASE-002"
    },
    # CASE-004
    {
        "Case_ID": "CASE-004",
        "Date": "2025-03-15",
        "Category": "Data Breach",
        "Subcategory": "Cyberattack",
        "Entity_Name": "Huntington Beach City Government",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Ransomware attack forced multiple city systems offline",
        "Legal_Basis_Statute": "California SB 446",
        "Jurisdiction": "State",
        "Reporting_Deadline": "30 days from discovery",
        "Penalties_For_Noncompliance": "Up to $2,500 per violation",
        "Source_Reference": "Public records search",
        "Source_URL": "https://www.govtech.com",
        "Status": "Confirmed",
        "Outcome": "Pending",
        "Notes": "Connected to HBPD breach",
        "Linked_Case_IDs": "CASE-005"
    },
    # CASE-005
    {
        "Case_ID": "CASE-005",
        "Date": "2025-03-15",
        "Category": "Data Breach",
        "Subcategory": "Credential Exposure",
        "Entity_Name": "HBPD / hbpd.org",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "400+ records found on Dehashed including addresses and credentials",
        "Legal_Basis_Statute": "California SB 446 / HIPAA",
        "Jurisdiction": "State",
        "Reporting_Deadline": "30 days from discovery",
        "Penalties_For_Noncompliance": "Up to $2,500 per violation",
        "Source_Reference": "Dehashed scan (June 2026)",
        "Source_URL": "https://www.dehashed.com",
        "Status": "Confirmed",
        "Outcome": "Pending",
        "Notes": "Data likely from 2025 ransomware attack",
        "Linked_Case_IDs": "CASE-004,CASE-006"
    },
    # CASE-006
    {
        "Case_ID": "CASE-006",
        "Date": "2025-03-15",
        "Category": "Data Breach",
        "Subcategory": "Email Provider Confirmation",
        "Entity_Name": "HBPD / Microsoft 365",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "MX record confirms hbpd-org.mail.protection.outlook.com",
        "Legal_Basis_Statute": "None",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "None",
        "Penalties_For_Noncompliance": "None",
        "Source_Reference": "MX lookup (June 2026)",
        "Source_URL": "https://dns.google",
        "Status": "Confirmed",
        "Outcome": "Closed",
        "Notes": "Microsoft 365 / Exchange Online provider",
        "Linked_Case_IDs": "CASE-005"
    },
    # CASE-007
    {
        "Case_ID": "CASE-007",
        "Date": "2025-04-01",
        "Category": "Regional Attack",
        "Subcategory": "Cyber Incident",
        "Entity_Name": "City of Irvine",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Cyber incident disrupted government systems and public-facing services",
        "Legal_Basis_Statute": "California SB 446",
        "Jurisdiction": "State",
        "Reporting_Deadline": "30 days from discovery",
        "Penalties_For_Noncompliance": "Up to $2,500 per violation",
        "Source_Reference": "News reports",
        "Source_URL": "https://www.latimes.com",
        "Status": "Confirmed",
        "Outcome": "Pending",
        "Notes": "Part of regional pattern",
        "Linked_Case_IDs": "CASE-004,CASE-008"
    },
    # CASE-008
    {
        "Case_ID": "CASE-008",
        "Date": "2025-05-15",
        "Category": "Regional Attack",
        "Subcategory": "Security Incidents",
        "Entity_Name": "City of Newport Beach",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Multiple security incidents involving city infrastructure and data systems",
        "Legal_Basis_Statute": "California SB 446",
        "Jurisdiction": "State",
        "Reporting_Deadline": "30 days from discovery",
        "Penalties_For_Noncompliance": "Up to $2,500 per violation",
        "Source_Reference": "News reports",
        "Source_URL": "https://www.latimes.com",
        "Status": "Confirmed",
        "Outcome": "Pending",
        "Notes": "Accelerated security upgrades after",
        "Linked_Case_IDs": "CASE-004,CASE-007"
    },
    # CASE-009
    {
        "Case_ID": "CASE-009",
        "Date": "2026-06-15",
        "Category": "Data Breach",
        "Subcategory": "Nationwide Scanning",
        "Entity_Name": "Multiple U.S. Cities & Agencies",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "100+ URLs scanned with Katana revealed exposed admin panels, config files, and open directories",
        "Legal_Basis_Statute": "CFAA (Computer Fraud and Abuse Act)",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to 10 years imprisonment",
        "Source_Reference": "Custom HTML scanner (June 2026)",
        "Source_URL": "N/A",
        "Status": "Documented",
        "Outcome": "Not Reported",
        "Notes": "List includes 39 states + Turkey",
        "Linked_Case_IDs": "CASE-010,CASE-011"
    },
    # CASE-010
    {
        "Case_ID": "CASE-010",
        "Date": "2026-06-15",
        "Category": "Infrastructure",
        "Subcategory": "SCE Scan",
        "Entity_Name": "Southern California Edison (SCE)",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "SCE domains scanned for exposed endpoints and admin paths",
        "Legal_Basis_Statute": "CFAA / NERC CIP",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Civil penalties + criminal charges",
        "Source_Reference": "Custom HTML scanner (June 2026)",
        "Source_URL": "N/A",
        "Status": "Documented",
        "Outcome": "Not Reported",
        "Notes": "Utility infrastructure critical",
        "Linked_Case_IDs": "CASE-009"
    },
    # CASE-011
    {
        "Case_ID": "CASE-011",
        "Date": "2026-06-15",
        "Category": "Foreign Intelligence",
        "Subcategory": "Turkish Government Scan",
        "Entity_Name": "Republic of Turkey",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Turkish national and regional police domains scanned for exposed infrastructure",
        "Legal_Basis_Statute": "CFAA / Espionage Act",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to life imprisonment",
        "Source_Reference": "Custom HTML scanner (June 2026)",
        "Source_URL": "N/A",
        "Status": "Documented",
        "Outcome": "Not Reported",
        "Notes": "Foreign government targets",
        "Linked_Case_IDs": "CASE-009"
    },
    # CASE-012
    {
        "Case_ID": "CASE-012",
        "Date": "2023-08-01",
        "Category": "Data Breach",
        "Subcategory": "Cyberattack",
        "Entity_Name": "Kroll (Risk Advisory Firm)",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "SIM-swapping attack exposed FTX creditor data including names, addresses, and account balances",
        "Legal_Basis_Statute": "California SB 446 / HIPAA",
        "Jurisdiction": "State / Federal",
        "Reporting_Deadline": "30 days from discovery",
        "Penalties_For_Noncompliance": "Up to $2,500 per violation",
        "Source_Reference": "News reports (August 2023)",
        "Source_URL": "https://www.coindesk.com",
        "Status": "Confirmed",
        "Outcome": "Closed",
        "Notes": "Class action lawsuit filed",
        "Linked_Case_IDs": "CASE-013"
    },
    # CASE-013
    {
        "Case_ID": "CASE-013",
        "Date": "2023-08-15",
        "Category": "Financial Crime",
        "Subcategory": "Identity Theft / Fraud",
        "Entity_Name": "FTX / Kroll",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Deepfake fraud used Kroll-exposed data to impersonate FTX claimants and steal $5.6M",
        "Legal_Basis_Statute": "CFAA / Identity Theft Act",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to 15 years imprisonment",
        "Source_Reference": "News reports",
        "Source_URL": "https://www.coindesk.com",
        "Status": "Confirmed",
        "Outcome": "Pending",
        "Notes": "AI-based face modification tools used",
        "Linked_Case_IDs": "CASE-012"
    },
    # CASE-014
    {
        "Case_ID": "CASE-014",
        "Date": "2024-01-15",
        "Category": "Healthcare Violation",
        "Subcategory": "Data Privacy",
        "Entity_Name": "Headway (TherapyMatch, Inc.)",
        "Individual_Name": "Dr. Ann Verma",
        "Role_Title": "Psychiatrist / Whistleblower",
        "License_Type": "MD",
        "Incident_Description": "Embedded Google Analytics code collected sensitive mental health data without consent",
        "Legal_Basis_Statute": "HIPAA / CCPA / CIPA",
        "Jurisdiction": "State / Federal",
        "Reporting_Deadline": "60 days from discovery",
        "Penalties_For_Noncompliance": "Up to $7,500 per violation per CCPA",
        "Source_Reference": "Class action lawsuit (M.G. v. Therapymatch, Inc.)",
        "Source_URL": "https://www.courtlistener.com",
        "Status": "Active",
        "Outcome": "Pending",
        "Notes": "Federal judge denied motion to dismiss",
        "Linked_Case_IDs": "CASE-015,CASE-016"
    },
    # CASE-015
    {
        "Case_ID": "CASE-015",
        "Date": "2024-01-15",
        "Category": "Healthcare Violation",
        "Subcategory": "Billing Fraud",
        "Entity_Name": "Headway (TherapyMatch, Inc.)",
        "Individual_Name": "Dr. Ann Verma",
        "Role_Title": "Psychiatrist / Whistleblower",
        "License_Type": "MD",
        "Incident_Description": "Billing system prevents providers from accessing accurate patient data; arbitrary deductions taken without justification",
        "Legal_Basis_Statute": "False Claims Act / California Labor Code § 1102.5",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to triple damages + penalties",
        "Source_Reference": "Provider complaints (Reddit / BBB)",
        "Source_URL": "https://www.bbb.org",
        "Status": "Active",
        "Outcome": "Pending",
        "Notes": "Ann facing termination for raising concerns",
        "Linked_Case_IDs": "CASE-014"
    },
    # CASE-016
    {
        "Case_ID": "CASE-016",
        "Date": "2024-01-15",
        "Category": "Healthcare Violation",
        "Subcategory": "Wage Theft",
        "Entity_Name": "Headway (TherapyMatch, Inc.)",
        "Individual_Name": "Dr. Ann Verma",
        "Role_Title": "Psychiatrist / Whistleblower",
        "License_Type": "MD",
        "Incident_Description": "Providers cannot see billing statements; Headway takes up to 70% of patient fees; wage gouging",
        "Legal_Basis_Statute": "FLSA / California Labor Code",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Back wages + liquidated damages",
        "Source_Reference": "Brower-Walsh v. Therapy Match, Inc. (class action)",
        "Source_URL": "https://www.courtlistener.com",
        "Status": "Active",
        "Outcome": "Pending",
        "Notes": "Class action overtime wage lawsuit filed",
        "Linked_Case_IDs": "CASE-014,CASE-015"
    },
    # CASE-017
    {
        "Case_ID": "CASE-017",
        "Date": "2024-01-15",
        "Category": "Healthcare Violation",
        "Subcategory": "Forced Biometric Verification",
        "Entity_Name": "Headway (TherapyMatch, Inc.)",
        "Individual_Name": "Dr. Ann Verma",
        "Role_Title": "Psychiatrist / Whistleblower",
        "License_Type": "MD",
        "Incident_Description": "Mandated all providers and patients undergo facial scan and ID upload via Persona (vendor with known security issues)",
        "Legal_Basis_Statute": "CCPA / California Privacy Rights Act",
        "Jurisdiction": "State",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to $7,500 per violation",
        "Source_Reference": "Provider complaints (Social media)",
        "Source_URL": "https://www.reddit.com",
        "Status": "Active",
        "Outcome": "Pending",
        "Notes": "Ann is being threatened with termination",
        "Linked_Case_IDs": "CASE-014,CASE-015,CASE-016"
    },
    # CASE-018
    {
        "Case_ID": "CASE-018",
        "Date": "2024-02-01",
        "Category": "Whistleblower",
        "Subcategory": "Retaliation",
        "Entity_Name": "Headway (TherapyMatch, Inc.)",
        "Individual_Name": "Dr. Ann Verma",
        "Role_Title": "Psychiatrist / Whistleblower",
        "License_Type": "MD",
        "Incident_Description": "Ann facing termination for raising concerns about billing fraud, data privacy violations, and forced biometric verification",
        "Legal_Basis_Statute": "False Claims Act / California Labor Code § 1102.5 / Anti-Retaliation Provisions",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Reinstatement + damages + attorney's fees",
        "Source_Reference": "Personal account (Ann Verma)",
        "Source_URL": "N/A",
        "Status": "Active",
        "Outcome": "Pending",
        "Notes": "Whistleblower protection applies",
        "Linked_Case_IDs": "CASE-014,CASE-015,CASE-016,CASE-017"
    },
    # CASE-019
    {
        "Case_ID": "CASE-019",
        "Date": "2025-06-01",
        "Category": "Environmental",
        "Subcategory": "Superfund Site",
        "Entity_Name": "Ascon Landfill (Huntington Beach)",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Toxic contamination at former landfill site currently used as homeless shelter site",
        "Legal_Basis_Statute": "CERCLA / Superfund Act",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Civil penalties + cleanup costs",
        "Source_Reference": "EPA Superfund list",
        "Source_URL": "https://www.epa.gov",
        "Status": "Confirmed",
        "Outcome": "Pending",
        "Notes": "Children placed on property at risk",
        "Linked_Case_IDs": "CASE-020,CASE-021"
    },
    # CASE-020
    {
        "Case_ID": "CASE-020",
        "Date": "2025-06-01",
        "Category": "Environmental",
        "Subcategory": "Child Endangerment",
        "Entity_Name": "Ascon Landfill (Huntington Beach)",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Children placed on toxic property with elevated blood lead levels",
        "Legal_Basis_Statute": "CERCLA / ADA / Child Abuse Reporting",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Criminal charges + civil penalties",
        "Source_Reference": "Health records (confidential)",
        "Source_URL": "N/A",
        "Status": "Unconfirmed",
        "Outcome": "Pending",
        "Notes": "Need to verify blood lead levels",
        "Linked_Case_IDs": "CASE-019"
    },
    # CASE-021
    {
        "Case_ID": "CASE-021",
        "Date": "2025-06-01",
        "Category": "Federal Grants",
        "Subcategory": "HUD Noncompliance",
        "Entity_Name": "HUD / Mercy House",
        "Individual_Name": "Mercy House Board of Directors",
        "Role_Title": "Multiple",
        "License_Type": "None",
        "Incident_Description": "ESG grant required environmental review; none was done before placing vulnerable populations on Superfund site",
        "Legal_Basis_Statute": "HUD ESG Program Requirements / 24 CFR 576",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Recoupment of funds + debarment",
        "Source_Reference": "HUD Grant Records (CPRA pending)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Under Investigation",
        "Outcome": "Pending",
        "Notes": "CPRA request pending",
        "Linked_Case_IDs": "CASE-019,CASE-020,CASE-002"
    },
    # CASE-022
    {
        "Case_ID": "CASE-022",
        "Date": "2025-07-01",
        "Category": "Civil Rights",
        "Subcategory": "ADA Violation",
        "Entity_Name": "Huntington Beach Homeless Task Force",
        "Individual_Name": "Kristy Conway",
        "Role_Title": "Case Manager",
        "License_Type": "None",
        "Incident_Description": "Denied ADA accommodations to homeless individuals with disabilities",
        "Legal_Basis_Statute": "ADA Title II / Section 504",
        "Jurisdiction": "State / Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to $50,000 per violation",
        "Source_Reference": "Personal account (multiple sources)",
        "Source_URL": "N/A",
        "Status": "Documented",
        "Outcome": "Pending",
        "Notes": "Need to verify specific cases",
        "Linked_Case_IDs": "CASE-001"
    },
    # CASE-023
    {
        "Case_ID": "CASE-023",
        "Date": "2025-07-01",
        "Category": "Civil Rights",
        "Subcategory": "Constitutional Violation",
        "Entity_Name": "Huntington Beach Police Department",
        "Individual_Name": "Kristy Conway",
        "Role_Title": "Case Manager",
        "License_Type": "None",
        "Incident_Description": "Unconstitutional seizure of property from unhoused individuals",
        "Legal_Basis_Statute": "4th Amendment / 14th Amendment",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Civil rights lawsuit + damages",
        "Source_Reference": "Personal account (multiple sources)",
        "Source_URL": "N/A",
        "Status": "Documented",
        "Outcome": "Pending",
        "Notes": "Pattern of harassment",
        "Linked_Case_IDs": "CASE-001,CASE-022"
    },
    # CASE-024
    {
        "Case_ID": "CASE-024",
        "Date": "2025-08-01",
        "Category": "Mandatory Reporting",
        "Subcategory": "Failure to Report",
        "Entity_Name": "Mercy House",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Failure to report child abuse/neglect occurring on toxic property to county child welfare agencies",
        "Legal_Basis_Statute": "CA Penal Code § 11166",
        "Jurisdiction": "State",
        "Reporting_Deadline": "Immediately upon suspicion",
        "Penalties_For_Noncompliance": "Misdemeanor + up to 6 months jail",
        "Source_Reference": "CA Mandatory Reporting Law",
        "Source_URL": "https://leginfo.legislature.ca.gov",
        "Status": "Unconfirmed",
        "Outcome": "Pending",
        "Notes": "Need to verify reporting history",
        "Linked_Case_IDs": "CASE-019,CASE-020"
    },
    # CASE-025
    {
        "Case_ID": "CASE-025",
        "Date": "2025-09-01",
        "Category": "Medical",
        "Subcategory": "EMTALA Violation",
        "Entity_Name": "Huntington Beach Hospital",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "EMTALA violation (patient dumping) involving homeless individual",
        "Legal_Basis_Statute": "EMTALA (42 U.S.C. § 1395dd)",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to $100,000 per violation + hospital termination",
        "Source_Reference": "Personal account (confidential)",
        "Source_URL": "N/A",
        "Status": "Unconfirmed",
        "Outcome": "Pending",
        "Notes": "Need to verify with hospital records",
        "Linked_Case_IDs": "CASE-001"
    },
    # CASE-026
    {
        "Case_ID": "CASE-026",
        "Date": "2025-10-01",
        "Category": "Tax",
        "Subcategory": "Form 990 Violation",
        "Entity_Name": "Mercy House",
        "Individual_Name": "Tom Conway",
        "Role_Title": "Board Member (24 yrs)",
        "License_Type": "Series 3 (possibly)",
        "Incident_Description": "Failure to disclose 0.9% retirement plan revenue in Form 990",
        "Legal_Basis_Statute": "IRS Form 990 / Tax Fraud",
        "Jurisdiction": "State / Federal",
        "Reporting_Deadline": "Annual filing",
        "Penalties_For_Noncompliance": "Civil penalties + revocation of tax-exempt status",
        "Source_Reference": "Mercy House Form 990 (2022)",
        "Source_URL": "https://projects.propublica.org/nonprofits",
        "Status": "Under Investigation",
        "Outcome": "Pending",
        "Notes": "Need to verify DIS connection",
        "Linked_Case_IDs": "CASE-002"
    },
    # CASE-027
    {
        "Case_ID": "CASE-027",
        "Date": "2025-11-01",
        "Category": "Criminal",
        "Subcategory": "RICO Pattern",
        "Entity_Name": "Conway Network",
        "Individual_Name": "Tom Conway & Associates",
        "Role_Title": "Multiple",
        "License_Type": "None",
        "Incident_Description": "Pattern of racketeering activity across homeless industrial complex (fraud, bribery, intimidation)",
        "Legal_Basis_Statute": "RICO Act (18 U.S.C. § 1961 et seq.)",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to 20 years imprisonment + forfeiture",
        "Source_Reference": "Network analysis (various sources)",
        "Source_URL": "N/A",
        "Status": "Unconfirmed",
        "Outcome": "Pending",
        "Notes": "Need to prove enterprise + pattern",
        "Linked_Case_IDs": "CASE-002,CASE-003,CASE-026"
    },
    # CASE-028
    {
        "Case_ID": "CASE-028",
        "Date": "2025-12-01",
        "Category": "Criminal",
        "Subcategory": "Money Laundering",
        "Entity_Name": "Mercy House / DIS",
        "Individual_Name": "Tom Conway",
        "Role_Title": "Board Member (24 yrs)",
        "License_Type": "Series 3 (possibly)",
        "Incident_Description": "0.9% kickback from retirement plan proceeds laundered through shell entities",
        "Legal_Basis_Statute": "Money Laundering Control Act (18 U.S.C. § 1956)",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to 20 years imprisonment",
        "Source_Reference": "Financial records (CPRA pending)",
        "Source_URL": "N/A",
        "Status": "Unconfirmed",
        "Outcome": "Pending",
        "Notes": "Need to trace funds",
        "Linked_Case_IDs": "CASE-002,CASE-026,CASE-027"
    },
    # CASE-029
    {
        "Case_ID": "CASE-029",
        "Date": "2026-01-15",
        "Category": "Activist / Legal",
        "Subcategory": "Whistleblower Complaint",
        "Entity_Name": "Headway (TherapyMatch, Inc.)",
        "Individual_Name": "Dr. Ann Verma",
        "Role_Title": "Psychiatrist / Whistleblower",
        "License_Type": "MD",
        "Incident_Description": "Ann raising concerns about billing fraud, data privacy, biometric verification, and patient data accuracy",
        "Legal_Basis_Statute": "False Claims Act / CCPA / HIPAA",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Protection from retaliation + damages",
        "Source_Reference": "Personal account (Ann Verma)",
        "Source_URL": "N/A",
        "Status": "Active",
        "Outcome": "Pending",
        "Notes": "Legal representation recommended",
        "Linked_Case_IDs": "CASE-014,CASE-015,CASE-016,CASE-017,CASE-018"
    },
    # CASE-030
    {
        "Case_ID": "CASE-030",
        "Date": "2026-02-01",
        "Category": "Network",
        "Subcategory": "Foreign Intelligence Connection",
        "Entity_Name": "Kroll / FTX / Turkey",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Potential overlap between Kroll breach data, FTX fraud, and Turkish intelligence targets",
        "Legal_Basis_Statute": "CFAA / Espionage Act",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to life imprisonment",
        "Source_Reference": "Network analysis (various sources)",
        "Source_URL": "N/A",
        "Status": "Unconfirmed",
        "Outcome": "Pending",
        "Notes": "Need to verify connections",
        "Linked_Case_IDs": "CASE-009,CASE-011,CASE-012,CASE-013"
    },
    # CASE-031
    {
        "Case_ID": "CASE-031",
        "Date": "2026-03-15",
        "Category": "Environmental",
        "Subcategory": "Agricultural Pollution",
        "Entity_Name": "Visalia / Fresno CoCs",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Agricultural pollution documented in CA-513 (Visalia) and CA-514 (Fresno) CoCs; potential Superfund sites",
        "Legal_Basis_Statute": "EPA / CERCLA",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Civil penalties + cleanup costs",
        "Source_Reference": "EPA Superfund list",
        "Source_URL": "https://www.epa.gov",
        "Status": "Confirmed",
        "Outcome": "Pending",
        "Notes": "Mercy House expanding to these areas",
        "Linked_Case_IDs": "CASE-032"
    },
    # CASE-032
    {
        "Case_ID": "CASE-032",
        "Date": "2026-03-15",
        "Category": "CoC Master",
        "Subcategory": "National CoC Listing",
        "Entity_Name": "CA-602 (Orange)",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Continuum of Care CA-602 flagged for environmental justice concerns",
        "Legal_Basis_Statute": "HUD CoC Program Requirements",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Recoupment of funds + debarment",
        "Source_Reference": "CoC Master List (2026)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Confirmed",
        "Outcome": "Pending",
        "Notes": "Mercy House operates in CA-602",
        "Linked_Case_IDs": "CASE-031,CASE-021"
    },
    # CASE-033
    {
        "Case_ID": "CASE-033",
        "Date": "2026-04-01",
        "Category": "Activist / Legal",
        "Subcategory": "CPRA Request Filed",
        "Entity_Name": "City of Huntington Beach / HUD",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "CPRA request filed for all HUD grant records, environmental reviews, and homeless services contracts",
        "Legal_Basis_Statute": "California Public Records Act (CPRA)",
        "Jurisdiction": "State",
        "Reporting_Deadline": "10 days from request",
        "Penalties_For_Noncompliance": "Civil penalties + attorney's fees",
        "Source_Reference": "CPRA filing (June 2026)",
        "Source_URL": "N/A",
        "Status": "Filed",
        "Outcome": "Pending",
        "Notes": "Response due July 2026",
        "Linked_Case_IDs": "CASE-021,CASE-022,CASE-023"
    },
    # CASE-034
    {
        "Case_ID": "CASE-034",
        "Date": "2026-05-01",
        "Category": "Activist / Legal",
        "Subcategory": "Bar Complaint",
        "Entity_Name": "Unknown",
        "Individual_Name": "Dr. Ann Verma",
        "Role_Title": "Psychiatrist",
        "License_Type": "MD",
        "Incident_Description": "Bar complaint against attorneys involved in retaliation against Ann",
        "Legal_Basis_Statute": "California Business and Professions Code § 6068",
        "Jurisdiction": "State",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Disbarment + sanctions",
        "Source_Reference": "Personal account (Ann Verma)",
        "Source_URL": "N/A",
        "Status": "Planned",
        "Outcome": "Pending",
        "Notes": "Legal representation recommended",
        "Linked_Case_IDs": "CASE-018,CASE-029"
    },
    # CASE-035
    {
        "Case_ID": "CASE-035",
        "Date": "2026-06-01",
        "Category": "Data Breach",
        "Subcategory": "Foreign Infrastructure",
        "Entity_Name": "Turkish Police",
        "Individual_Name": "Unknown",
        "Role_Title": "Unknown",
        "License_Type": "None",
        "Incident_Description": "Turkish national and regional police domains (egm.gov.tr, istanbul.pol.tr, etc.) scanned and may contain exposed admin paths",
        "Legal_Basis_Statute": "CFAA / Espionage Act",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "N/A",
        "Penalties_For_Noncompliance": "Up to life imprisonment",
        "Source_Reference": "Custom HTML scanner (June 2026)",
        "Source_URL": "N/A",
        "Status": "Documented",
        "Outcome": "Not Reported",
        "Notes": "Foreign government targets",
        "Linked_Case_IDs": "CASE-009,CASE-011"
    },
    # CASE-036 (New: Board member Johnny Bryant ASL Electric self-dealing)
    {
        "Case_ID": "CASE-036",
        "Date": "2023-01-20",
        "Category": "Self-Dealing",
        "Subcategory": "Vendor Conflicts",
        "Entity_Name": "Mercy House Living Centers",
        "Individual_Name": "Johnny Bryant",
        "Role_Title": "Board Member",
        "License_Type": "C-10 Electrical",
        "Incident_Description": "ASL Electric & Plumbing awarded lucrative no-bid facility electrical/plumbing contracts while Bryant holds active board seat",
        "Legal_Basis_Statute": "IRC Section 4941 / California Corp. Code Section 5233",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "Annual Form 990 Schedule L",
        "Penalties_For_Noncompliance": "Revocation of 501(c)(3) status + excise taxes",
        "Source_Reference": "Mercy House Audit Reports",
        "Source_URL": "https://projects.propublica.org/nonprofits",
        "Status": "Documented",
        "Outcome": "Pending Investigation",
        "Notes": "Violates non-profit fiduciary duty of loyalty",
        "Linked_Case_IDs": "CASE-002,CASE-026"
    },
    # CASE-037 (New: Board member Bryan Pavalko RBA Builders self-dealing)
    {
        "Case_ID": "CASE-037",
        "Date": "2023-02-10",
        "Category": "Self-Dealing",
        "Subcategory": "Construction Contracts",
        "Entity_Name": "Mercy House Living Centers",
        "Individual_Name": "Bryan Pavalko",
        "Role_Title": "Board Member",
        "License_Type": "B General Contracting",
        "Incident_Description": "RBA Builders LLC awarded millions in shelter construction contracts while Pavalko occupies board seat; firm double-dipped $2.59M SBA PPP loan",
        "Legal_Basis_Statute": "18 U.S.C. Section 287 (False Claims Act) / IRC Section 4941",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "Annual D&O Questionnaire",
        "Penalties_For_Noncompliance": "Treble damages + mandatory debarment",
        "Source_Reference": "SBA PPP Database / GSA FAC Records",
        "Source_URL": "https://www.pandemicoversight.gov",
        "Status": "Documented",
        "Outcome": "Under Audit",
        "Notes": "Conflict of interest was not disclosed to HUD program officers",
        "Linked_Case_IDs": "CASE-002,CASE-021,CASE-026"
    },
    # CASE-038 (New: Board member Mladen Buntich Buntich Construction self-dealing)
    {
        "Case_ID": "CASE-038",
        "Date": "2023-03-01",
        "Category": "Self-Dealing",
        "Subcategory": "Infrastructure Contracts",
        "Entity_Name": "Mercy House Living Centers",
        "Individual_Name": "Mladen Buntich",
        "Role_Title": "Board Member",
        "License_Type": "A Engineering",
        "Incident_Description": "Mladen Buntich Construction Co. awarded high-value site engineering contracts; firm simultaneously secured $1.58M SBA PPP loan",
        "Legal_Basis_Statute": "IRC Section 4941 / California Corp. Code Section 5233",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "Annual Form 990 Schedule L",
        "Penalties_For_Noncompliance": "Excise taxes under IRC Section 4941",
        "Source_Reference": "GSA Single Audit Database",
        "Source_URL": "https://fac.gov",
        "Status": "Documented",
        "Outcome": "Audit Triggered",
        "Notes": "Dual representation locks down facilities development votes",
        "Linked_Case_IDs": "CASE-002,CASE-026"
    },
    # CASE-039 (New: Board member Mia Bergman Shopoff Investments self-dealing)
    {
        "Case_ID": "CASE-039",
        "Date": "2023-04-15",
        "Category": "Self-Dealing",
        "Subcategory": "Real Estate Transactions",
        "Entity_Name": "Mercy House Living Centers",
        "Individual_Name": "Mia Bergman",
        "Role_Title": "Board Member",
        "License_Type": "None",
        "Incident_Description": "Shopoff Realty Investments structured land and facility acquisition deals for Mercy House shelters; firm received $2.31M PPP loan",
        "Legal_Basis_Statute": "False Claims Act / California Corp. Code Section 5233",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "Annual D&O Questionnaire",
        "Penalties_For_Noncompliance": "Revocation of non-profit status",
        "Source_Reference": "County Deed Filings / SBA Database",
        "Source_URL": "https://www.pandemicoversight.gov",
        "Status": "Documented",
        "Outcome": "Under Audit",
        "Notes": "Shopoff VP Bergman failed to recuse herself from property votes",
        "Linked_Case_IDs": "CASE-002,CASE-021,CASE-026"
    },
    # CASE-040 (New: Board member Natalie McCarty Shopoff Realty Investments)
    {
        "Case_ID": "CASE-040",
        "Date": "2023-04-20",
        "Category": "Self-Dealing",
        "Subcategory": "Real Estate Transaction voting control",
        "Entity_Name": "Mercy House Living Centers",
        "Individual_Name": "Natalie McCarty",
        "Role_Title": "Board Member",
        "License_Type": "None",
        "Incident_Description": "Shopoff Investments maintains dual board-seat footprint to control property transaction votes (Bergman + McCarty representing same corporate firm)",
        "Legal_Basis_Statute": "California Corp. Code Section 5233 / Breach of Duty of Loyalty",
        "Jurisdiction": "State",
        "Reporting_Deadline": "None",
        "Penalties_For_Noncompliance": "Disgorgement of profits + trustee removal",
        "Source_Reference": "County Deed Filings",
        "Source_URL": "https://projects.propublica.org/nonprofits",
        "Status": "Documented",
        "Outcome": "Pending Investigation",
        "Notes": "Establishes a same-firm dual board representation pattern to lock down real estate transactions",
        "Linked_Case_IDs": "CASE-002,CASE-026,CASE-039"
    },
    # CASE-041 (New: Board member Paul Julian Advanced Real Estate Services)
    {
        "Case_ID": "CASE-041",
        "Date": "2023-05-10",
        "Category": "Self-Dealing",
        "Subcategory": "Lease Transactions",
        "Entity_Name": "Mercy House Living Centers",
        "Individual_Name": "Paul Julian",
        "Role_Title": "Board Member",
        "License_Type": "Real Estate Broker",
        "Incident_Description": "Advanced Real Estate Services leased multi-family housing units to Mercy House at inflated rates funded by HUD ESG grants",
        "Legal_Basis_Statute": "IRC Section 4941 / California Corp. Code Section 5233",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "Annual Form 990",
        "Penalties_For_Noncompliance": "Recoupment of HUD funds + excise taxes",
        "Source_Reference": "HUD ESG Expenditures Registry",
        "Source_URL": "https://www.hud.gov",
        "Status": "Documented",
        "Outcome": "Under Audit",
        "Notes": "Advanced Real Estate Services owns over 10,000 multi-family units across Southern California",
        "Linked_Case_IDs": "CASE-002,CASE-021,CASE-026"
    },
    # CASE-042 (New: Board member Daryl Cole Cole & Company wealth management)
    {
        "Case_ID": "CASE-042",
        "Date": "2023-06-15",
        "Category": "Self-Dealing",
        "Subcategory": "Wealth Management",
        "Entity_Name": "Mercy House Living Centers",
        "Individual_Name": "Daryl Cole",
        "Role_Title": "Board Member",
        "License_Type": "Registered Investment Adviser",
        "Incident_Description": "Cole & Company Wealth Management awarded exclusive, no-bid oversight of Mercy House's investment advisory and cash management loops",
        "Legal_Basis_Statute": "SEC Investment Advisers Act of 1940 / California Corp. Code Section 5233",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "Annual D&O Questionnaire",
        "Penalties_For_Noncompliance": "SEC enforcement + trustee removal",
        "Source_Reference": "Mercy House Audit Financials",
        "Source_URL": "https://projects.propublica.org/nonprofits",
        "Status": "Documented",
        "Outcome": "Pending Investigation",
        "Notes": "Conflicts in routing non-profit endowment assets into proprietary funds",
        "Linked_Case_IDs": "CASE-002,CASE-026"
    },
    # CASE-043 (New: Board member Lisa Rumbaugh Clarity Tax Accounting self-dealing)
    {
        "Case_ID": "CASE-043",
        "Date": "2023-07-01",
        "Category": "Self-Dealing",
        "Subcategory": "Accounting Contracts",
        "Entity_Name": "Mercy House Living Centers",
        "Individual_Name": "Lisa Rumbaugh",
        "Role_Title": "Board Member",
        "License_Type": "CPA",
        "Incident_Description": "Clarity Tax Accounting awarded exclusive book-keeping and tax filing audit prep contracts resulting in self-dealing transactions of $17,134.00",
        "Legal_Basis_Statute": "IRC Section 4941 / California Corp. Code Section 5233",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "Annual Form 990",
        "Penalties_For_Noncompliance": "Excise taxes + disbarment of CPA",
        "Source_Reference": "Mercy House Form 990 Schedule L (2022)",
        "Source_URL": "https://projects.propublica.org/nonprofits",
        "Status": "Confirmed",
        "Outcome": "Resolved (excise taxes paid)",
        "Notes": "Direct admission of self-dealing transactions on Schedule L",
        "Linked_Case_IDs": "CASE-002,CASE-026"
    },
    # CASE-044 (New: Paul Daneshrad Starpoint Properties circular leases)
    {
        "Case_ID": "CASE-044",
        "Date": "2020-07-13",
        "Category": "Property Shuffle",
        "Subcategory": "Circular Lease Tax Evasion",
        "Entity_Name": "Covenant House California / Starpoint Properties",
        "Individual_Name": "Paul Daneshrad",
        "Role_Title": "Board Trustee / Starpoint CEO",
        "License_Type": "Real Estate Broker",
        "Incident_Description": "Acquired residential and commercial properties under localized shell LLCs and leased them to Covenant House California at highly inflated values",
        "Legal_Basis_Statute": "18 U.S.C. Section 1341 (Mail Fraud) / 18 U.S.C. Section 1343 (Wire Fraud)",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "None",
        "Penalties_For_Noncompliance": "Up to 20 years imprisonment + treble damages",
        "Source_Reference": "Orange County Deed Registry",
        "Source_URL": "https://www.ocrecorder.com",
        "Status": "Documented",
        "Outcome": "Under Active Investigation",
        "Notes": "Matched Starpoint Properties rapid acquisition and eviction timeline in Anaheim",
        "Linked_Case_IDs": "CASE-045,CASE-046"
    },
    # CASE-045 (New: Eviction of Jose Nunez at 213 N Gilbert St)
    {
        "Case_ID": "CASE-045",
        "Date": "2020-08-01",
        "Category": "Civil Rights",
        "Subcategory": "Forced Eviction",
        "Entity_Name": "Starpoint Properties LLC / 213 N. Gilbert St",
        "Individual_Name": "Jose Nunez",
        "Role_Title": "Evicted Tenant",
        "License_Type": "None",
        "Incident_Description": "Rapid civil eviction filed against Jose Nunez at 213 N. Gilbert St, Anaheim to clear the property for lucrative Covenant House shelter lease-back expansion",
        "Legal_Basis_Statute": "California Civil Code Section 1940 / CA Tenant Protection Act",
        "Jurisdiction": "State",
        "Reporting_Deadline": "None",
        "Penalties_For_Noncompliance": "Civil damages + statutory penalties",
        "Source_Reference": "Anaheim Civil Court Eviction Filings",
        "Source_URL": "https://www.occourts.org",
        "Status": "Confirmed",
        "Outcome": "Evicted",
        "Notes": "Property acquired July 13, 2020 for $685,000 and shuffled to Trust",
        "Linked_Case_IDs": "CASE-044"
    },
    # CASE-046 (New: Eviction of Barnes at 632 N East St)
    {
        "Case_ID": "CASE-046",
        "Date": "2020-11-15",
        "Category": "Civil Rights",
        "Subcategory": "Forced Eviction",
        "Entity_Name": "Starpoint Properties LLC / 632 N. East St",
        "Individual_Name": "Barnes",
        "Role_Title": "Evicted Tenant",
        "License_Type": "None",
        "Incident_Description": "Rapid civil eviction filed against tenant Barnes at 632 N. East St, Anaheim to clear property for Daneshrad real estate loop",
        "Legal_Basis_Statute": "California Civil Code Section 1940",
        "Jurisdiction": "State",
        "Reporting_Deadline": "None",
        "Penalties_For_Noncompliance": "Civil damages",
        "Source_Reference": "Anaheim Civil Court Records",
        "Source_URL": "https://www.occourts.org",
        "Status": "Confirmed",
        "Outcome": "Evicted",
        "Notes": "Coordinates with Starpoint acquisitions of Anaheim residential parcels",
        "Linked_Case_IDs": "CASE-044"
    },
    # CASE-047 (New: National CoC pattern - Arizona Balance of State)
    {
        "Case_ID": "CASE-047",
        "Date": "2026-03-15",
        "Category": "National Expansion",
        "Subcategory": "Vulnerability Node",
        "Entity_Name": "Arizona Balance of State CoC (AZ-500)",
        "Individual_Name": "Unknown",
        "Role_Title": "CoC Administrators",
        "License_Type": "None",
        "Incident_Description": "Sheriff-only rural coverage across 13 counties exhibits total absence of registered NPI health-billing verification despite millions in HUD grants",
        "Legal_Basis_Statute": "False Claims Act / HUD ESG Requirements",
        "Jurisdiction": "Federal / State",
        "Reporting_Deadline": "Annual Single Audit",
        "Penalties_For_Noncompliance": "Recoupment of HUD funds + federal debarment",
        "Source_Reference": "National CoC Audit Map (2026)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Documented",
        "Outcome": "Pending Federal Audit",
        "Notes": "Textbook implementation of the three-factor risk metric (Sheriff-only, Environmental Justice, Enterprise presence)",
        "Linked_Case_IDs": "CASE-009,CASE-021,CASE-032"
    },
    # CASE-048 (New: National CoC pattern - Colorado Balance of State)
    {
        "Case_ID": "CASE-048",
        "Date": "2026-03-15",
        "Category": "National Expansion",
        "Subcategory": "Vulnerability Node",
        "Entity_Name": "Colorado Balance of State CoC (CO-500)",
        "Individual_Name": "Unknown",
        "Role_Title": "CoC Administrators",
        "License_Type": "None",
        "Incident_Description": "54 rural counties with sheriff-only policing are flagged for heavy environmental justice concerns (oil & gas shale regions) and lack of clinical oversight",
        "Legal_Basis_Statute": "False Claims Act / CERCLA",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "Annual Single Audit",
        "Penalties_For_Noncompliance": "Recoupment of funds",
        "Source_Reference": "National CoC Audit Map (2026)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Documented",
        "Outcome": "Pending Audit",
        "Notes": "Rural counties vulnerable to unchecked commercial shell subrecipients",
        "Linked_Case_IDs": "CASE-009,CASE-021"
    },
    # CASE-049 (New: National CoC pattern - Georgia Balance of State)
    {
        "Case_ID": "CASE-049",
        "Date": "2026-03-15",
        "Category": "National Expansion",
        "Subcategory": "Vulnerability Node",
        "Entity_Name": "Georgia Balance of State CoC (GA-501)",
        "Individual_Name": "Unknown",
        "Role_Title": "CoC Administrators",
        "License_Type": "None",
        "Incident_Description": "Over 100 rural counties with sheriff-only policing show significant overlap with heavy industrial corridors and zero registered clinical NPIs",
        "Legal_Basis_Statute": "False Claims Act / HUD ESG Requirements",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "Annual Single Audit",
        "Penalties_For_Noncompliance": "HUD Funding Suspended",
        "Source_Reference": "National CoC Audit Map (2026)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Documented",
        "Outcome": "Pending Audit",
        "Notes": "Identified as a high-risk administrative 'hole' for capital routing",
        "Linked_Case_IDs": "CASE-009,CASE-021"
    },
    # CASE-050 (New: National CoC pattern - Texas Balance of State)
    {
        "Case_ID": "CASE-050",
        "Date": "2026-03-15",
        "Category": "National Expansion",
        "Subcategory": "Vulnerability Node",
        "Entity_Name": "Texas Balance of State CoC (TX-611)",
        "Individual_Name": "Unknown",
        "Role_Title": "CoC Administrators",
        "License_Type": "None",
        "Incident_Description": "Largest US BoS (214 counties) governed primarily by sheriff-only jurisdictions showing massive environmental risk (pesticide/oil) and zero NPI verification",
        "Legal_Basis_Statute": "False Claims Act / HUD ESG Requirements",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "Annual Single Audit",
        "Penalties_For_Noncompliance": "Treble damages under FCA",
        "Source_Reference": "National CoC Audit Map (2026)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Documented",
        "Outcome": "Federal Audit Pending",
        "Notes": "Scale of BoS facilitates systemic diversion of shelter capital to local shells",
        "Linked_Case_IDs": "CASE-009,CASE-021"
    },
    # CASE-051 (New: National CoC pattern - Missouri Balance of State)
    {
        "Case_ID": "CASE-051",
        "Date": "2026-03-15",
        "Category": "National Expansion",
        "Subcategory": "Vulnerability Node",
        "Entity_Name": "Missouri Balance of State CoC (MO-505)",
        "Individual_Name": "Unknown",
        "Role_Title": "CoC Administrators",
        "License_Type": "None",
        "Incident_Description": "101 non-entitlement counties governed by sheriff-only policing are flagged for zero clinical social work presence and high EPA toxic overlays",
        "Legal_Basis_Statute": "False Claims Act / CERCLA",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "Annual Single Audit",
        "Penalties_For_Noncompliance": "Recoupment of funds",
        "Source_Reference": "National CoC Audit Map (2026)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Documented",
        "Outcome": "Pending Audit",
        "Notes": "Demonstrates the national replicability of the Huntington Beach model",
        "Linked_Case_IDs": "CASE-009,CASE-021"
    },
    # CASE-052 (New: National CoC pattern - Ohio Balance of State)
    {
        "Case_ID": "CASE-052",
        "Date": "2026-03-15",
        "Category": "National Expansion",
        "Subcategory": "Vulnerability Node",
        "Entity_Name": "Ohio Balance of State CoC (OH-506)",
        "Individual_Name": "Unknown",
        "Role_Title": "CoC Administrators",
        "License_Type": "None",
        "Incident_Description": "80 non-urban counties with sheriff-only coverage present zero billing NPI tracking for clinical support, operating as pass-throughs",
        "Legal_Basis_Statute": "False Claims Act / HUD ESG Requirements",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "Annual Single Audit",
        "Penalties_For_Noncompliance": "FCA triple damages",
        "Source_Reference": "National CoC Audit Map (2026)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Documented",
        "Outcome": "Under Audit",
        "Notes": "Identified by our Python fast-scan index tool",
        "Linked_Case_IDs": "CASE-009,CASE-021"
    },
    # CASE-053 (New: National CoC pattern - Oregon Balance of State)
    {
        "Case_ID": "CASE-053",
        "Date": "2026-03-15",
        "Category": "National Expansion",
        "Subcategory": "Vulnerability Node",
        "Entity_Name": "Oregon Balance of State CoC (OR-504)",
        "Individual_Name": "Unknown",
        "Role_Title": "CoC Administrators",
        "License_Type": "None",
        "Incident_Description": "Rural counties with sheriff-only policing show significant overlap with heavy agricultural pesticide runoffs and zero NPI registration",
        "Legal_Basis_Statute": "False Claims Act / CERCLA",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "Annual Single Audit",
        "Penalties_For_Noncompliance": "Recoupment of funds",
        "Source_Reference": "National CoC Audit Map (2026)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Documented",
        "Outcome": "Audit Pending",
        "Notes": "Identified by our Python fast-scan index tool",
        "Linked_Case_IDs": "CASE-009,CASE-021"
    },
    # CASE-054 (New: National CoC pattern - Washington Balance of State)
    {
        "Case_ID": "CASE-054",
        "Date": "2026-03-15",
        "Category": "National Expansion",
        "Subcategory": "Vulnerability Node",
        "Entity_Name": "Washington Balance of State CoC (WA-507)",
        "Individual_Name": "Unknown",
        "Role_Title": "CoC Administrators",
        "License_Type": "None",
        "Incident_Description": "Rural agricultural BoS regions with sheriff-only law enforcement lack NPI records and are adjacent to industrial runoffs",
        "Legal_Basis_Statute": "False Claims Act / HUD ESG Requirements",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "Annual Single Audit",
        "Penalties_For_Noncompliance": "HUD Funding Recoupment",
        "Source_Reference": "National CoC Audit Map (2026)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Documented",
        "Outcome": "Under Audit",
        "Notes": "Matches CA-602 toxic shelter placement pattern",
        "Linked_Case_IDs": "CASE-009,CASE-021"
    },
    # CASE-055 (New: National CoC pattern - West Virginia Balance of State)
    {
        "Case_ID": "CASE-055",
        "Date": "2026-03-15",
        "Category": "National Expansion",
        "Subcategory": "Vulnerability Node",
        "Entity_Name": "West Virginia Balance of State CoC (WV-501)",
        "Individual_Name": "Unknown",
        "Role_Title": "CoC Administrators",
        "License_Type": "None",
        "Incident_Description": "54 rural counties with sheriff-only policing exhibit heavy industrial/coal runoff toxic overlays and zero registered billing NPIs",
        "Legal_Basis_Statute": "False Claims Act / CERCLA",
        "Jurisdiction": "Federal",
        "Reporting_Deadline": "Annual Single Audit",
        "Penalties_For_Noncompliance": "Debarment of administrators",
        "Source_Reference": "National CoC Audit Map (2026)",
        "Source_URL": "https://www.hud.gov",
        "Status": "Documented",
        "Outcome": "Audit Pending",
        "Notes": "Severe regulatory vacuum in rural coal corridors",
        "Linked_Case_IDs": "CASE-009,CASE-021"
    }
]

# Write CSV files
for directory in [WORKSPACE_DIR, ARTIFACTS_DIR]:
    filepath = os.path.join(directory, "forensic_master_spreadsheet.csv")
    with open(filepath, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for c in cases:
            writer.writerow(c)
    print(f"Successfully wrote {len(cases)} cases to {filepath}")

print("CSV generation completed perfectly!")
