import os
import re
import pandas as pd
from google.cloud import bigquery

# Base scratch directory containing the scanned spreadsheets and file indices
scratch_dir = r"C:\Users\HP\.gemini\antigravity\brain\71e7b1d1-f50b-477e-a713-942e8319b97d\scratch"

client = bigquery.Client()
dataset_id = "project-743aab84-f9a5-4ec7-954.national_audits"

# Helper function to extract source folder from file paths
def get_source_folder(path_val):
    if not isinstance(path_val, str):
        return "Unknown"
    # Matches common directories like C:\OSINT... or C:\Users\HP\...
    m = re.match(r'^([a-zA-Z]:\\[^\\]+)', path_val)
    if m:
        return m.group(1)
    return "Unknown"

# Define Table Schemas
schemas = {
    "local_scan_file_inventory": [
        bigquery.SchemaField("source_folder", "STRING"),
        bigquery.SchemaField("path", "STRING"),
        bigquery.SchemaField("size", "INTEGER"),
        bigquery.SchemaField("modified_utc", "STRING"),
        bigquery.SchemaField("sha256", "STRING"),
    ],
    "local_scan_extracted_text": [
        bigquery.SchemaField("source_folder", "STRING"),
        bigquery.SchemaField("path", "STRING"),
        bigquery.SchemaField("extracted_text", "STRING"),
    ],
    "local_scan_emails": [
        bigquery.SchemaField("source_folder", "STRING"),
        bigquery.SchemaField("email", "STRING"),
    ],
    "local_scan_phones": [
        bigquery.SchemaField("source_folder", "STRING"),
        bigquery.SchemaField("phone", "STRING"),
    ],
    "local_scan_numbers": [
        bigquery.SchemaField("source_folder", "STRING"),
        bigquery.SchemaField("number", "STRING"),
    ],
    "local_scan_matches": [
        bigquery.SchemaField("source_folder", "STRING"),
        bigquery.SchemaField("type", "STRING"),
        bigquery.SchemaField("value", "STRING"),
        bigquery.SchemaField("sheet", "STRING"),
        bigquery.SchemaField("column", "STRING"),
        bigquery.SchemaField("row_index", "INTEGER"),
        bigquery.SchemaField("matched_value_or_score", "STRING"),
    ]
}

# Create Tables if they do not exist
for table_name, schema in schemas.items():
    table_ref = f"{dataset_id}.{table_name}"
    try:
        client.get_table(table_ref)
        print(f"Table {table_name} already exists.")
    except Exception:
        table = bigquery.Table(table_ref, schema=schema)
        client.create_table(table)
        print(f"Table {table_name} created successfully.")

# Find all Excel output sheets generated by local scans
excel_files = [f for f in os.listdir(scratch_dir) if f.startswith('osint_') and f.endswith('.xlsx')]
print(f"Found local scan spreadsheets: {excel_files}")

# Row buffers to ingest via JSON insertion
inventory_rows = []
text_rows = []
email_rows = []
phone_rows = []
number_rows = []
match_rows = []

for ef in excel_files:
    ef_path = os.path.join(scratch_dir, ef)
    print(f"\nProcessing spreadsheet: {ef}")
    try:
        xl = pd.ExcelFile(ef_path)
        
        # 1. File Inventory
        if 'FileInventory' in xl.sheet_names:
            df = xl.parse('FileInventory')
            for _, r in df.iterrows():
                path_val = r.get('Path')
                if pd.notna(path_val):
                    src = get_source_folder(path_val)
                    sz = r.get('Size')
                    inventory_rows.append({
                        "source_folder": src,
                        "path": str(path_val),
                        "size": int(sz) if pd.notna(sz) and str(sz).isdigit() else None,
                        "modified_utc": str(r.get('ModifiedUTC')) if pd.notna(r.get('ModifiedUTC')) else None,
                        "sha256": str(r.get('SHA256')) if pd.notna(r.get('SHA256')) else None
                    })
                    
        # 2. Extracted Text Index
        if 'ExtractedTextIndex' in xl.sheet_names:
            df = xl.parse('ExtractedTextIndex')
            for _, r in df.iterrows():
                path_val = r.get('Path')
                txt_val = r.get('ExtractedText')
                if pd.notna(path_val):
                    src = get_source_folder(path_val)
                    text_rows.append({
                        "source_folder": src,
                        "path": str(path_val),
                        "extracted_text": str(txt_val)[:32000] if pd.notna(txt_val) else None  # Limit length for safety
                    })
                    
        # 3. Emails
        if 'Emails' in xl.sheet_names:
            df = xl.parse('Emails')
            # Look for the email column (usually named 'Email')
            col = 'Email' if 'Email' in df.columns else (df.columns[0] if len(df.columns) > 0 else None)
            if col:
                for _, r in df.iterrows():
                    em = r.get(col)
                    if pd.notna(em):
                        email_rows.append({
                            "source_folder": "Parsed Indicators",
                            "email": str(em)
                        })
                        
        # 4. Phones
        if 'Phones' in xl.sheet_names:
            df = xl.parse('Phones')
            col = 'Phone' if 'Phone' in df.columns else (df.columns[0] if len(df.columns) > 0 else None)
            if col:
                for _, r in df.iterrows():
                    ph = r.get(col)
                    if pd.notna(ph):
                        phone_rows.append({
                            "source_folder": "Parsed Indicators",
                            "phone": str(ph)
                        })
                        
        # 5. Numbers
        if 'Numbers' in xl.sheet_names:
            df = xl.parse('Numbers')
            col = 'Number' if 'Number' in df.columns else (df.columns[0] if len(df.columns) > 0 else None)
            if col:
                for _, r in df.iterrows():
                    num = r.get(col)
                    if pd.notna(num):
                        number_rows.append({
                            "source_folder": "Parsed Indicators",
                            "number": str(num)
                        })
                        
        # 6. Matches
        if 'Matches' in xl.sheet_names:
            df = xl.parse('Matches')
            for _, r in df.iterrows():
                val = r.get('Value')
                if pd.notna(val):
                    match_rows.append({
                        "source_folder": "Parsed Matches",
                        "type": str(r.get('Type')) if pd.notna(r.get('Type')) else None,
                        "value": str(val),
                        "sheet": str(r.get('Sheet')) if pd.notna(r.get('Sheet')) else None,
                        "column": str(r.get('Column')) if pd.notna(r.get('Column')) else None,
                        "row_index": int(r.get('RowIndex')) if pd.notna(r.get('RowIndex')) and str(r.get('RowIndex')).isdigit() else None,
                        "matched_value_or_score": str(r.get('MatchedValueOrScore')) if pd.notna(r.get('MatchedValueOrScore')) else None
                    })
    except Exception as e:
        print(f"Error processing {ef}: {e}")

# Also process individual CSV file inventories if they have extra information
csv_files = [f for f in os.listdir(scratch_dir) if f.startswith('dl_file_index_') and f.endswith('.csv')]
print(f"Found CSV file indices: {csv_files}")

for cf in csv_files:
    cf_path = os.path.join(scratch_dir, cf)
    try:
        df = pd.read_csv(cf_path)
        for _, r in df.iterrows():
            path_val = r.get('Path')
            if pd.notna(path_val):
                src = get_source_folder(path_val)
                sz = r.get('Size')
                inventory_rows.append({
                    "source_folder": src,
                    "path": str(path_val),
                    "size": int(sz) if pd.notna(sz) and str(sz).isdigit() else None,
                    "modified_utc": str(r.get('ModifiedUTC')) if pd.notna(r.get('ModifiedUTC')) else None,
                    "sha256": str(r.get('SHA256')) if pd.notna(r.get('SHA256')) else None
                })
    except Exception as e:
        print(f"Error processing CSV {cf}: {e}")

# De-duplicate inventory rows
seen_inventory_paths = set()
unique_inventory_rows = []
for row in inventory_rows:
    if row["path"] not in seen_inventory_paths:
        seen_inventory_paths.add(row["path"])
        unique_inventory_rows.append(row)

# Load to BigQuery in Chunks
def load_to_bq(table_name, rows):
    table_ref = f"{dataset_id}.{table_name}"
    chunk_size = 500
    total_loaded = 0
    for i in range(0, len(rows), chunk_size):
        chunk = rows[i:i+chunk_size]
        errors = client.insert_rows_json(table_ref, chunk)
        if errors:
            print(f"Error inserting chunk into {table_name}: {errors[:5]}")
        else:
            total_loaded += len(chunk)
    print(f"Ingested {total_loaded} rows into {table_name}.")

print("\nStarting ingestion of local scans and file indexes into BigQuery...")
if unique_inventory_rows:
    load_to_bq("local_scan_file_inventory", unique_inventory_rows)
if text_rows:
    load_to_bq("local_scan_extracted_text", text_rows)
if email_rows:
    load_to_bq("local_scan_emails", email_rows)
if phone_rows:
    load_to_bq("local_scan_phones", phone_rows)
if number_rows:
    load_to_bq("local_scan_numbers", number_rows)
if match_rows:
    load_to_bq("local_scan_matches", match_rows)

print("\nAll local folder scan data successfully uploaded to BigQuery!")
